level_0 = {
    'terrain': 'venv/levels/0/level_0_terrain.csv',
    'terrain_without_collide': 'venv/levels/0/level_0_terrain_without_collide.csv',
    'coins': 'venv/levels/0/level_0_coins.csv',
    'fg_palms': 'venv/levels/0/level_0_fg_palms.csv',
    'bg_palms': 'venv/levels/0/level_0_bg_palms.csv',
    'crates': 'venv/levels/0/level_0_crates.csv',
    'enemies': 'venv/levels/0/level_0_enemies.csv',
    'constraints': 'venv/levels/0/level_0_constraints.csv',
    'player': 'venv/levels/0/level_0_player.csv',
    'grass': 'venv/levels/0/level_0_grass.csv',
    'node_pos': (140, 220),
    'unlock': 1,
    'node_graphics': 'venv/graphics/overworld/0'}
level_1 = {
    'terrain': 'venv/levels/0/level_0_terrain.csv',
    'terrain_without_collide': 'venv/levels/0/level_0_terrain_without_collide.csv',
    'coins': 'venv/levels/0/level_0_coins.csv',
    'fg_palms': 'venv/levels/0/level_0_fg_palms.csv',
    'bg_palms': 'venv/levels/0/level_0_bg_palms.csv',
    'crates': 'venv/levels/0/level_0_crates.csv',
    'enemies': 'venv/levels/0/level_0_enemies.csv',
    'constraints': 'venv/levels/0/level_0_constraints.csv',
    'player': 'venv/levels/0/level_0_player.csv',
    'grass': 'venv/levels/0/level_0_grass.csv',
    'node_pos': (325, 480),
    'unlock': 2,
    'node_graphics': 'venv/graphics/overworld/1'}
level_2 = {
    'terrain': 'venv/levels/0/level_0_terrain.csv',
    'terrain_without_collide': 'venv/levels/0/level_0_terrain_without_collide.csv',
    'coins': 'venv/levels/0/level_0_coins.csv',
    'fg_palms': 'venv/levels/0/level_0_fg_palms.csv',
    'bg_palms': 'venv/levels/0/level_0_bg_palms.csv',
    'crates': 'venv/levels/0/level_0_crates.csv',
    'enemies': 'venv/levels/0/level_0_enemies.csv',
    'constraints': 'venv/levels/0/level_0_constraints.csv',
    'player': 'venv/levels/0/level_0_player.csv',
    'grass': 'venv/levels/0/level_0_grass.csv',
    'node_pos': (510, 220),
    'unlock': 3,
    'node_graphics': 'venv/graphics/overworld/2'}
level_3 = {
    'terrain': 'venv/levels/0/level_0_terrain.csv',
    'terrain_without_collide': 'venv/levels/0/level_0_terrain_without_collide.csv',
    'coins': 'venv/levels/0/level_0_coins.csv',
    'fg_palms': 'venv/levels/0/level_0_fg_palms.csv',
    'bg_palms': 'venv/levels/0/level_0_bg_palms.csv',
    'crates': 'venv/levels/0/level_0_crates.csv',
    'enemies': 'venv/levels/0/level_0_enemies.csv',
    'constraints': 'venv/levels/0/level_0_constraints.csv',
    'player': 'venv/levels/0/level_0_player.csv',
    'grass': 'venv/levels/0/level_0_grass.csv',
    'node_pos': (695, 480),
    'unlock': 4,
    'node_graphics': 'venv/graphics/overworld/3'}
level_4 = {
    'terrain': 'venv/levels/0/level_0_terrain.csv',
    'terrain_without_collide': 'venv/levels/0/level_0_terrain_without_collide.csv',
    'coins': 'venv/levels/0/level_0_coins.csv',
    'fg_palms': 'venv/levels/0/level_0_fg_palms.csv',
    'bg_palms': 'venv/levels/0/level_0_bg_palms.csv',
    'crates': 'venv/levels/0/level_0_crates.csv',
    'enemies': 'venv/levels/0/level_0_enemies.csv',
    'constraints': 'venv/levels/0/level_0_constraints.csv',
    'player': 'venv/levels/0/level_0_player.csv',
    'grass': 'venv/levels/0/level_0_grass.csv',
    'node_pos': (880, 220),
    'unlock': 5,
    'node_graphics': 'venv/graphics/overworld/4'}
level_5 = {
    'terrain': 'venv/levels/0/level_0_terrain.csv',
    'terrain_without_collide': 'venv/levels/0/level_0_terrain_without_collide.csv',
    'coins': 'venv/levels/0/level_0_coins.csv',
    'fg_palms': 'venv/levels/0/level_0_fg_palms.csv',
    'bg_palms': 'venv/levels/0/level_0_bg_palms.csv',
    'crates': 'venv/levels/0/level_0_crates.csv',
    'enemies': 'venv/levels/0/level_0_enemies.csv',
    'constraints': 'venv/levels/0/level_0_constraints.csv',
    'player': 'venv/levels/0/level_0_player.csv',
    'grass': 'venv/levels/0/level_0_grass.csv',
    'node_pos': (1075, 480),
    'unlock': 5,
    'node_graphics': 'venv/graphics/overworld/5'}

levels = {0: level_0, 1: level_1, 2: level_2, 3: level_3, 4: level_4, 5: level_5}
